
import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Inter , Outfit} from 'next/font/google'


const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = { 
  title: "TransitXpert",
  description: "Generated by TransitXpert",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ClerkProvider>
    <html lang="en">
      <body className = {outfit.className}>
        <NavBar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
